"""Textes d'interface centralisés de l'application."""

APPLICATION_NAME = "SBBN Toolbox"
APPLICATION_TAGLINE = "Vos outils PDF, simplement et localement"

NAV_HOME = "Accueil"
NAV_IMAGES = "Images vers PDF"
NAV_PDF = "Fusionner des PDF"
NAV_SETTINGS = "Paramètres"

HOME_EYEBROW = "BOÎTE À OUTILS PDF"
HOME_TITLE = "Que souhaitez-vous faire ?"
HOME_DESCRIPTION = (
    "Préparez vos documents directement sur votre ordinateur. "
    "Aucun fichier n’est envoyé sur Internet."
)
HOME_IMAGES_DESCRIPTION = "Assemblez vos images JPG, PNG ou BMP dans un document PDF."
HOME_PDF_DESCRIPTION = "Réorganisez les pages de plusieurs documents dans un PDF unique."
OPEN_TOOL = "Ouvrir l’outil"
LOCAL_PROCESSING_NOTE = "Traitement local · Aucun envoi de document"

IMAGES_TITLE = "Images vers PDF"
IMAGES_DESCRIPTION = "Ajoutez des images, puis organisez-les avant de créer votre document."
IMAGES_DROP_TITLE = "Déposez vos images ici"
IMAGES_DROP_DESCRIPTION = "Formats acceptés : JPG, JPEG, PNG et BMP"
ADD_IMAGES = "Ajouter des images"
CREATE_PDF = "Créer le PDF"
CLEAR_IMAGES = "Vider la sélection"
CANCEL_CONVERSION = "Annuler"
ROTATE_IMAGE = "Tourner de 90°"
REMOVE_IMAGE = "Retirer"
IMAGES_EMPTY_TITLE = "Aucune image ajoutée"
IMAGES_EMPTY_DESCRIPTION = "Vos images apparaîtront ici dans l’ordre du document final."
IMAGE_FILES_FILTER = "Images (*.jpg *.jpeg *.png *.bmp)"
PDF_FILES_FILTER = "Documents PDF (*.pdf)"
OUTPUT_OPTIONS_TITLE = "Options de sortie"
PAGE_SIZE_LABEL = "Taille de page"
PAGE_SIZE_ORIGINAL = "Taille originale"
PAGE_SIZE_A4 = "A4"
ORIENTATION_LABEL = "Orientation"
ORIENTATION_AUTO = "Automatique"
ORIENTATION_PORTRAIT = "Portrait"
ORIENTATION_LANDSCAPE = "Paysage"
MARGINS_LABEL = "Marges (mm)"
CONVERSION_PROGRESS = "Conversion en cours…"
CONVERSION_CANCELLED = "La conversion a été annulée."
CONVERSION_SUCCESS_TITLE = "PDF créé"
CONVERSION_SUCCESS_MESSAGE = "Le PDF a été créé avec succès :\n{path}"
OPEN_FOLDER = "Ouvrir le dossier"
CLOSE = "Fermer"
QUIT_CONFIRM_TITLE = "Quitter l’application ?"
QUIT_CONFIRM_MESSAGE = "Une sélection n’a pas encore été exportée. Voulez-vous vraiment quitter ?"
SHORTCUT_ADD_TOOLTIP = "Ajouter des fichiers (Ctrl+O)"
SHORTCUT_REMOVE_TOOLTIP = "Retirer la sélection (Suppr)"
SHORTCUT_SELECT_ALL_TOOLTIP = "Tout sélectionner (Ctrl+A)"
SHORTCUT_SAVE_TOOLTIP = "Enregistrer (Ctrl+S)"
SHORTCUT_CANCEL_TOOLTIP = "Annuler l’opération (Échap)"
SAVE_PDF_TITLE = "Enregistrer le PDF"
OVERWRITE_TITLE = "Remplacer le fichier ?"
OVERWRITE_MESSAGE = "Le fichier existe déjà. Voulez-vous le remplacer ?"
IMPORT_ERROR_TITLE = "Image non importée"

PDF_TITLE = "Fusionner des PDF"
PDF_DESCRIPTION = "Rassemblez et réorganisez toutes les pages dans un seul document."
PDF_DROP_TITLE = "Déposez vos PDF ici"
PDF_DROP_DESCRIPTION = "Vous pourrez ensuite réorganiser chaque page"
ADD_PDF = "Ajouter des PDF"
ADD_MORE_PDF = "Ajouter d’autres PDF"
MERGE_PDF = "Fusionner les PDF"
CLEAR_PDF_PAGES = "Vider les pages"
ROTATE_SELECTED_PAGES = "Tourner de 90°"
REMOVE_SELECTED_PAGES = "Retirer les pages"
REORDER_PDF_DOCUMENTS = "Réorganiser les PDF entiers"
CANCEL_PDF_OPERATION = "Annuler"
PDF_EMPTY_TITLE = "Aucun PDF ajouté"
PDF_EMPTY_DESCRIPTION = "Les pages de vos documents apparaîtront ici."
PDF_FILES_INPUT_FILTER = "Documents PDF (*.pdf)"
PDF_LOADING_PROGRESS = "Chargement progressif des pages…"
PDF_MERGE_PROGRESS = "Fusion en cours…"
PDF_OPERATION_CANCELLED = "L’opération PDF a été annulée."
PDF_IMPORT_ERROR_TITLE = "PDF non importé"
PDF_SAVE_TITLE = "Enregistrer le PDF fusionné"
PDF_OVERWRITE_TITLE = "Remplacer le fichier ?"
PDF_OVERWRITE_MESSAGE = "Le fichier existe déjà. Voulez-vous le remplacer ?"
PDF_SUCCESS_TITLE = "PDF fusionné"
PDF_SUCCESS_MESSAGE = "Le PDF a été créé avec succès :\n{path}"

SETTINGS_TITLE = "Paramètres"
SETTINGS_DESCRIPTION = "Personnalisez le comportement de SBBN Toolbox."
DATA_SECTION_TITLE = "Dossier de données"
DATA_SECTION_DESCRIPTION = (
    "Choisissez où conserver les préférences et le journal technique de l’application."
)
DATA_PATH_LABEL = "Emplacement actuel"
DATA_PATH_PLACEHOLDER = "Non configuré"
CHOOSE_FOLDER = "Choisir un dossier"
USE_NEW_LOCATION = "Utiliser le nouvel emplacement"
MIGRATE_SETTINGS = "Déplacer les paramètres actuels"
SELECT_DATA_FOLDER = "Sélectionner le dossier de données"
FIRST_LAUNCH_TITLE = "Choisir le dossier de données"
FIRST_LAUNCH_MESSAGE = (
    "SBBN Toolbox doit créer son dossier de données. Vous pouvez utiliser le dossier data "
    "à côté du programme ou choisir un autre emplacement."
)
USE_DEFAULT_DATA = "Utiliser le dossier data"
CHOOSE_OTHER_DATA = "Choisir un autre emplacement"
DATA_LOCATION_UPDATED = "Le dossier de données a été mis à jour."
DATA_LOCATION_MIGRATED = "Les paramètres ont été déplacés vers le nouvel emplacement."
DATA_LOCATION_ERROR_TITLE = "Dossier de données inaccessible"
DATA_LOCATION_RECOVERY = (
    "Le dossier configuré ne peut pas être utilisé. Choisissez un autre emplacement."
)
INTERFACE_SECTION_TITLE = "Interface"
INTERFACE_SECTION_DESCRIPTION = "L’application suit automatiquement la mise à l’échelle Windows."
SCALE_LABEL = "Mise à l’échelle"
SCALE_VALUE = "Automatique (100 %, 125 % et 150 %)"

PHASE_PLACEHOLDER_MESSAGE = "Cette action sera disponible dans une prochaine phase."
DROP_PLACEHOLDER_MESSAGE = "Dépôt détecté — aucun fichier n’a été chargé."
